In [1]:
import pandas as pd
import numpy as np
pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
dates = pd.date_range("20130101", periods=6)

dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

df

                   A         B         C         D
2013-01-01 -0.063143  0.991708 -0.633600  0.541148
2013-01-02 -0.101305  0.009676  0.943130  1.217773
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316
2013-01-05 -0.383162 -1.075500  0.525509  0.100581
2013-01-06 -0.000078  0.994221  0.346672  0.460280

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [6]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [7]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [8]:
df

                   A         B         C         D
2013-01-01 -0.063143  0.991708 -0.633600  0.541148
2013-01-02 -0.101305  0.009676  0.943130  1.217773
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316
2013-01-05 -0.383162 -1.075500  0.525509  0.100581
2013-01-06 -0.000078  0.994221  0.346672  0.460280

In [9]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.to_numpy

<bound method DataFrame.to_numpy of                    A         B         C         D
2013-01-01 -0.063143  0.991708 -0.633600  0.541148
2013-01-02 -0.101305  0.009676  0.943130  1.217773
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316
2013-01-05 -0.383162 -1.075500  0.525509  0.100581
2013-01-06 -0.000078  0.994221  0.346672  0.460280>

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.046334 -0.209389  0.092765  0.346515
std    1.080341  1.065881  0.608259  0.543903
min   -1.546101 -1.560645 -0.633600 -0.414316
25%   -0.312698 -0.960574 -0.361107  0.118842
50%   -0.082224 -0.303059  0.065602  0.316952
75%   -0.015845  0.746200  0.480799  0.520931
max    1.815786  0.994221  0.943130  1.217773

In [12]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.063143   -0.101305   -1.546101    1.815786   -0.383162   -0.000078
B    0.991708    0.009676   -0.615795   -1.560645   -1.075500    0.994221
C   -0.633600    0.943130   -0.409654   -0.215469    0.525509    0.346672
D    0.541148    1.217773    0.173625   -0.414316    0.100581    0.460280

In [13]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  0.541148 -0.633600  0.991708 -0.063143
2013-01-02  1.217773  0.943130  0.009676 -0.101305
2013-01-03  0.173625 -0.409654 -0.615795 -1.546101
2013-01-04 -0.414316 -0.215469 -1.560645  1.815786
2013-01-05  0.100581  0.525509 -1.075500 -0.383162
2013-01-06  0.460280  0.346672  0.994221 -0.000078

In [14]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316
2013-01-05 -0.383162 -1.075500  0.525509  0.100581
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625
2013-01-02 -0.101305  0.009676  0.943130  1.217773
2013-01-01 -0.063143  0.991708 -0.633600  0.541148
2013-01-06 -0.000078  0.994221  0.346672  0.460280

In [15]:
df["A"]

2013-01-01   -0.063143
2013-01-02   -0.101305
2013-01-03   -1.546101
2013-01-04    1.815786
2013-01-05   -0.383162
2013-01-06   -0.000078
Freq: D, Name: A, dtype: float64

In [16]:
df.loc[dates[0]]

A   -0.063143
B    0.991708
C   -0.633600
D    0.541148
Name: 2013-01-01 00:00:00, dtype: float64

In [17]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01 -0.063143  0.991708
2013-01-02 -0.101305  0.009676
2013-01-03 -1.546101 -0.615795
2013-01-04  1.815786 -1.560645
2013-01-05 -0.383162 -1.075500
2013-01-06 -0.000078  0.994221

In [18]:
df.loc[dates[0], "A"]

-0.06314312021664437

In [19]:
df.at[dates[0], "A"]

-0.06314312021664437

In [20]:
df.iloc[3]

A    1.815786
B   -1.560645
C   -0.215469
D   -0.414316
Name: 2013-01-04 00:00:00, dtype: float64

In [21]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  1.815786 -1.560645
2013-01-05 -0.383162 -1.075500

In [22]:
df[df["A"] > 0]

                   A         B         C         D
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316

In [23]:
df2 = df.copy()

In [24]:
df2["E"] = ["one", "one", "two", "three", "four", "three"]

df2

                   A         B         C         D      E
2013-01-01 -0.063143  0.991708 -0.633600  0.541148    one
2013-01-02 -0.101305  0.009676  0.943130  1.217773    one
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625    two
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316  three
2013-01-05 -0.383162 -1.075500  0.525509  0.100581   four
2013-01-06 -0.000078  0.994221  0.346672  0.460280  three

In [25]:
df2[df2["E"].isin(["two", "four"])]

                   A         B         C         D     E
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625   two
2013-01-05 -0.383162 -1.075500  0.525509  0.100581  four

In [26]:
df2["E"].unique()

array(['one', 'two', 'three', 'four'], dtype=object)

In [27]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])

df1.loc[dates[0] : dates[1], "E"] = 1

df1

                   A         B         C         D    E
2013-01-01 -0.063143  0.991708 -0.633600  0.541148  1.0
2013-01-02 -0.101305  0.009676  0.943130  1.217773  1.0
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625  NaN
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316  NaN

In [28]:
df1.dropna(how="any")

                   A         B        C         D    E
2013-01-01 -0.063143  0.991708 -0.63360  0.541148  1.0
2013-01-02 -0.101305  0.009676  0.94313  1.217773  1.0

In [29]:
df1.fillna(value=5)

                   A         B         C         D    E
2013-01-01 -0.063143  0.991708 -0.633600  0.541148  1.0
2013-01-02 -0.101305  0.009676  0.943130  1.217773  1.0
2013-01-03 -1.546101 -0.615795 -0.409654  0.173625  5.0
2013-01-04  1.815786 -1.560645 -0.215469 -0.414316  5.0

In [30]:
pd.isna(df1)

                A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

In [31]:
df.mean()

A   -0.046334
B   -0.209389
C    0.092765
D    0.346515
dtype: float64

In [32]:
df.mean(axis=1)

2013-01-01    0.209028
2013-01-02    0.517318
2013-01-03   -0.599481
2013-01-04   -0.093661
2013-01-05   -0.208143
2013-01-06    0.450274
Freq: D, dtype: float64

In [33]:
df.agg(lambda x: np.mean(x)* 5.6)

A   -0.259470
B   -1.172579
C    0.519483
D    1.940485
dtype: float64

In [34]:
df.transform(lambda x: x * 101.2)

                     A           B          C           D
2013-01-01   -6.390084  100.360837 -64.120276   54.764220
2013-01-02  -10.252107    0.979244  95.444711  123.238642
2013-01-03 -156.465388  -62.318418 -41.456937   17.570844
2013-01-04  183.757538 -157.937311 -21.805421  -41.928810
2013-01-05  -38.775966 -108.840581  53.181461   10.178812
2013-01-06   -0.007928  100.615125  35.083236   46.580313

In [35]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [36]:
df = pd.DataFrame(np.random.randn(10, 4))

In [37]:
df

          0         1         2         3
0 -0.033701 -1.727812  0.438171  1.236032
1  1.203291  0.276752  1.311636 -1.171487
2  0.515787 -1.658161  0.917057  0.404012
3 -0.805515 -0.884945 -0.548851  1.349188
4  0.317928 -0.833589 -1.114763 -2.022763
5  1.868926  0.967593  0.382527  1.139837
6  1.271823  1.921895 -1.531290  0.283604
7 -0.365243  0.655022  0.016110 -0.216448
8 -0.455630  0.221183  0.915747 -0.775865
9  0.418784 -0.455576 -0.930864 -0.220472

In [38]:
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

          0         1         2         3
0 -0.033701 -1.727812  0.438171  1.236032
1  1.203291  0.276752  1.311636 -1.171487
2  0.515787 -1.658161  0.917057  0.404012
3 -0.805515 -0.884945 -0.548851  1.349188
4  0.317928 -0.833589 -1.114763 -2.022763
5  1.868926  0.967593  0.382527  1.139837
6  1.271823  1.921895 -1.531290  0.283604
7 -0.365243  0.655022  0.016110 -0.216448
8 -0.455630  0.221183  0.915747 -0.775865
9  0.418784 -0.455576 -0.930864 -0.220472

In [39]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

In [40]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [41]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [42]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)

In [43]:
df

     A      B         C         D
0  foo    one  0.233140  0.982827
1  bar    one -0.617186 -0.611241
2  foo    two  0.625924 -0.330605
3  bar  three  0.520077  0.511858
4  foo    two  0.445327 -1.283358
5  bar    two  1.406453 -0.038074
6  foo    one  0.155998  2.664835
7  foo  three -0.538602  0.691972

In [44]:
df.groupby("A").sum()

                     B         C         D
A
bar        onethreetwo  1.309344 -0.137457
foo  onetwotwoonethree  0.921787  2.725671

In [45]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]


index = pd.MultiIndex.from_arrays(arrays, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df

                     A         B
first second
bar   one    -1.545591  1.613194
      two     0.022944 -1.279084
baz   one     1.574107 -0.520721
      two     0.774697 -0.224196
foo   one    -0.960844 -0.559125
      two    -0.479662  0.193973
qux   one    -0.192739 -1.031988
      two    -0.215653 -0.322583

In [46]:
stacked = df.stack()

In [47]:
stacked

first  second
bar    one     A   -1.545591
               B    1.613194
       two     A    0.022944
               B   -1.279084
baz    one     A    1.574107
               B   -0.520721
       two     A    0.774697
               B   -0.224196
foo    one     A   -0.960844
               B   -0.559125
       two     A   -0.479662
               B    0.193973
qux    one     A   -0.192739
               B   -1.031988
       two     A   -0.215653
               B   -0.322583
dtype: float64

In [48]:
stacked.unstack()

                     A         B
first second
bar   one    -1.545591  1.613194
      two     0.022944 -1.279084
baz   one     1.574107 -0.520721
      two     0.774697 -0.224196
foo   one    -0.960844 -0.559125
      two    -0.479662  0.193973
qux   one    -0.192739 -1.031988
      two    -0.215653 -0.322583

In [49]:
stacked.unstack(1)

second        one       two
first
bar   A -1.545591  0.022944
      B  1.613194 -1.279084
baz   A  1.574107  0.774697
      B -0.520721 -0.224196
foo   A -0.960844 -0.479662
      B -0.559125  0.193973
qux   A -0.192739 -0.215653
      B -1.031988 -0.322583

In [50]:
stacked.unstack(0)

first          bar       baz       foo       qux
second
one    A -1.545591  1.574107 -0.960844 -0.192739
       B  1.613194 -0.520721 -0.559125 -1.031988
two    A  0.022944  0.774697 -0.479662 -0.215653
       B -1.279084 -0.224196  0.193973 -0.322583

In [51]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)


df

        A  B    C         D         E
0     one  A  foo  0.606296  0.841731
1     one  B  foo  0.298915  0.625455
2     two  C  foo  0.135332  1.371666
3   three  A  bar  0.720647  0.972313
4     one  B  bar  0.749602 -1.305790
5     one  C  bar  1.218998 -0.547800
6     two  A  foo  0.123787 -1.404689
7   three  B  foo  1.482379  2.270608
8     one  C  foo -1.313812  0.247424
9     one  A  bar -0.599035 -0.904784
10    two  B  bar  2.577938 -0.857785
11  three  C  bar -0.190474  1.023131

In [52]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B
one   A -0.599035  0.606296
      B  0.749602  0.298915
      C  1.218998 -1.313812
three A  0.720647       NaN
      B       NaN  1.482379
      C -0.190474       NaN
two   A       NaN  0.123787
      B  2.577938       NaN
      C       NaN  0.135332

In [53]:
rng = pd.date_range("1/1/2012", periods=100, freq="s")

ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

ts.resample("5Min").sum()

2012-01-01    26380
Freq: 5T, dtype: int32

In [54]:
ts

2012-01-01 00:00:00    294
2012-01-01 00:00:01    195
2012-01-01 00:00:02     95
2012-01-01 00:00:03    424
2012-01-01 00:00:04    433
                      ...
2012-01-01 00:01:35    280
2012-01-01 00:01:36    485
2012-01-01 00:01:37    345
2012-01-01 00:01:38    305
2012-01-01 00:01:39    404
Freq: S, Length: 100, dtype: int32

In [55]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")

ts = pd.Series(np.random.randn(len(rng)), rng)

ts

2012-03-06    0.159098
2012-03-07    1.633790
2012-03-08   -0.476800
2012-03-09    0.131987
2012-03-10   -2.011941
Freq: D, dtype: float64

In [56]:
ts_utc = ts.tz_localize("UTC")

In [57]:
ts_utc

2012-03-06 00:00:00+00:00    0.159098
2012-03-07 00:00:00+00:00    1.633790
2012-03-08 00:00:00+00:00   -0.476800
2012-03-09 00:00:00+00:00    0.131987
2012-03-10 00:00:00+00:00   -2.011941
Freq: D, dtype: float64

In [58]:
ts_utc.tz_convert("US/Eastern")

2012-03-05 19:00:00-05:00    0.159098
2012-03-06 19:00:00-05:00    1.633790
2012-03-07 19:00:00-05:00   -0.476800
2012-03-08 19:00:00-05:00    0.131987
2012-03-09 19:00:00-05:00   -2.011941
Freq: D, dtype: float64

In [60]:
rng

DatetimeIndex(['2012-03-06', '2012-03-07', '2012-03-08', '2012-03-09',
               '2012-03-10'],
              dtype='datetime64[ns]', freq='D')

In [61]:
rng + pd.offsets.BusinessDay(5)

DatetimeIndex(['2012-03-13', '2012-03-14', '2012-03-15', '2012-03-16',
               '2012-03-16'],
              dtype='datetime64[ns]', freq=None)

In [64]:
df = pd.DataFrame(
{"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]})

In [66]:
df["grade"] = df["raw_grade"].astype("category")

In [67]:
df

   id raw_grade grade
0   1         a     a
1   2         b     b
2   3         b     b
3   4         a     a
4   5         a     a
5   6         e     e

In [68]:
new_categories = ["very good", "good", "very bad"]

df["grade"] = df["grade"].cat.rename_categories(new_categories)

In [69]:
df

   id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [70]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)


df["grade"]

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): ['very bad', 'bad', 'medium', 'good', 'very good']

In [71]:
df.sort_values(by="grade")

   id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good

In [72]:
df.groupby("grade", observed=False).size()

grade
very bad     1
bad          0
medium       0
good         2
very good    3
dtype: int64